version: '3'

services:
  consul-server:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
    volumes:
      - ./server:/etc/consul.d
    command: consul agent --config-file /etc/consul.d/default.json
  consul-agent:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
    volumes:
      - ./agent:/etc/consul.d
    command: consul agent -join consul-server --config-file /etc/consul.d/default.json
    links:
      - "consul-server"
